name: Build Android Shared Library (.so)

on:
  workflow_dispatch:
  push:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android NDK
        uses: ndkify/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Install CMake & Ninja
        run: sudo apt-get install -y cmake ninja-build

      - name: Build with CMake
        run: |
          mkdir build
          cd build
          cmake .. \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_LATEST_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-24 \
            -DCMAKE_BUILD_TYPE=Release \
            -G Ninja
          ninja

      - name: Upload Output Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-mod-files
          path: |
            build/*.so
            config/config.json
